chezmoi: added awscli setup

diff --git a/run_once_install-packages.sh.tmpl b/run_once_install-packages.sh.tmpl
--- a/run_once_install-packages.sh.tmpl
+++ b/run_once_install-packages.sh.tmpl
@@ -46,4 +46,48 @@ brew install elgato-wave-link \
 mkdir -p ~/.tmux/plugins
 git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
 
+# aws cli setup
+mkdir ~/.aws/
+
+#!/bin/bash
+
+# Create the AWS helper script using cat and heredoc
+cat <<EOF > ~/.aws/aws-pass-helper.sh
+#!/bin/bash
+
+# Path where the credentials are stored in pass
+BASE_PATH=hosting/aws.amazon.com
+
+# Define the profile from the environment
+AWS_PROFILE=\${AWS_PROFILE:-default}
+
+# Fetch credentials from pass
+ACCESS_KEY_ID=\$(pass \$BASE_PATH/\$AWS_PROFILE/access_key_id)
+SECRET_ACCESS_KEY=\$(pass \$BASE_PATH/\$AWS_PROFILE/secret_access_key)
+
+# Check that we have the required keys
+if [[ -z "\$ACCESS_KEY_ID" || -z "\$SECRET_ACCESS_KEY" ]]; then
+  echo "Error: Missing AWS credentials for profile \$AWS_PROFILE" >&2
+  exit 1
+fi
+
+# Output the credentials in JSON format required by awscli
+cat <<JSON
+{
+  "Version": 1,
+  "AccessKeyId": "\$ACCESS_KEY_ID",
+  "SecretAccessKey": "\$SECRET_ACCESS_KEY"
+}
+JSON
+EOF
+chmod +x ~/.aws/aws-pass-helper.sh
+
+
+# Home will be pre-processed here as the current home 
+cat <<EOF > ~/.aws/config
+[profile blorgh/jeduardo]
+region = eu-central-1
+credential_process = $HOME/.aws/aws-pass-helper.sh
+EOF
+
 {{ end -}}
